---

- name: Enable text selection within quicklook
  osx_defaults: domain=com.apple.finder key=QLEnableTextSelection type=bool value=true state=present

- name: Show hidden files in finder by default
  osx_defaults: domain=com.apple.finder key=AppleShowAllFiles type=bool value=true state=present

- name: Reduce keyboard key repeat delay
  osx_defaults: key=InitialKeyRepeat type=int value=25 state=present

- name: Increase keyboard key repeat speed
  osx_defaults: key=KeyRepeat type=int value=2

- name: Create system aliases
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    line: 'alias {{ item.key }}=\"{{ item.value }}\"'
  with_dict: "{{ aliases }}"
  vars:
    aliases:
      cat: bat
      ls: exa