---
- name: Create global .gitignore
  shell: cp {{ playbook_dir }}/roles/git/files/.gitignore_global {{ ansible_env.HOME }}

- name: Create Git config
  git_config: scope=global name={{ item.name }} value={{ item.value }}
  with_items:
    - { name: 'user.name', value: '{{ git_name }}' }
    - { name: 'user.email', value: '{{ git_email }}' }
    - { name: 'core.pager', value: 'diff-so-fancy | less --tabs=1,5 -R' }
    - { name: 'core.excludesfile', value: '{{ ansible_env.HOME }}/.gitignore_global' }
    - { name: 'core.editor', value: 'nano' }
    - { name: 'color.branch', value: 'always' }
    - { name: 'color.diff', value: 'auto' }
    - { name: 'color.interactive', value: 'always' }
    - { name: 'color.status', value: 'always' }
    - { name: 'color.ui', value: 'always' }
    - { name: 'color.diff-highlight.oldNormal', value: 'red bold' }
    - { name: 'color.diff-highlight.oldHighlight', value: 'red bold 52' }
    - { name: 'color.diff-highlight.newNormal', value: 'green bold' }
    - { name: 'color.diff-highlight.newHighlight', value: 'green bold 22' }
    - { name: 'color.diff.meta', value: '11' }
    - { name: 'color.diff.frag', value: 'magenta bold' }
    - { name: 'color.diff.commit', value: 'yellow bold' }
    - { name: 'color.diff.old', value: 'red bold' }
    - { name: 'color.diff.new', value: 'green bold' }
    - { name: 'color.diff.whitespace', value: 'red reverse' }
    - { name: 'core.autocrlf', value: 'input' }
    - { name: 'core.whitespace', value: 'trailing-space,space-before-tab,cr-at-eol' }
    - { name: 'alias.co', value: 'checkout' }
    - { name: 'alias.cm', value: 'commit -m' }
    - { name: 'alias.st', value: 'status' }
    - { name: 'alias.force', value: 'push -f' }
    - { name: 'alias.last', value: 'log -1 HEAD' }
    - { name: 'alias.undo-commit', value: 'reset HEAD~' }
    - { name: 'alias.cp', value: 'cherry-pick' }
    - { name: 'alias.prune', value: 'fetch --prune' }
    - { name: 'format.pretty', value: 'oneline' }
    - { name: 'push.default', value: 'current' }
    - { name: 'push.followTags', value: 'true' }
    - { name: 'tag.sort', value: 'version:refname' }
    - { name: 'pull.rebase', value: 'true' }
    - { name: 'branch.autosetuprebase', value: 'always' }