---
- name: Ensure nvm is present
  shell: command -v nvm > /dev/null || curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: '{{ ansible_env.HOME }}/.nvm/nvm.sh'

- name: Install and alias node
  shell: ". {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ node_version }} && nvm alias default {{ node_version }} && nvm use default"

- name: Install yarn
  shell: curl -o- -L https://yarnpkg.com/install.sh | bash
  args:
    warn: false # ignores Ansible warning about using `curl`